name: donno
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.1+1
  http: ^0.12.2
  cupertino_icons: ^0.1.3
  marquee_flutter: ^0.1.4
  shimmer: ^1.1.1
  image_picker: ^0.6.7+7
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Title
      fonts:
        - asset: fonts/title.ttf
    - family: SubTitle
      fonts:
        - asset: fonts/subtitle.ttf
    - family: body
      fonts:
        - asset: fonts/body.ttf
    - family: Myanmar
      fonts:
        - asset: fonts/zawgyi.ttf


